### ISSUE TITLE
 L.. Details: u'unknown' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by turnerdb** [chrismaddalena/GoReport#12]
Received the following:

[!] There was a problem processing campaign ID 129!
L.. Details: u'unknown' does not appear to be an IPv4 or IPv6 address

Is there a place I can look for more detailed log information for what is happening?  I saw the other issue regarding GeoMapping but not sure if this is in the same realm.  I downloaded the requirements.txt file and updated my version in case the fix was in there already.

Let me know.

Thanks!

**Comment by chrismaddalena** [comment]
Hey there,

I can look at this now that the holidays are behind us. I intend to implement logging into GoReport alongside some more verbose error messaging. Right now the errors are too generic. It tries to provide details, but you don't get a full traceback and sometimes the details are so barebones they are worthless.

This error is a new one for me. It should not have anything to do with the geolocation because the try/except block that produces this warning occurs when GoReport is checking-in with GoPhish to verify the campaign ID exists and is accessible.

I'll assume campaign 129 is a valid campaign, but please do double check that to make sure it can be viewed in GoPhish.

Are other campaigns processed, or is 129 the only one you tried?

What else is displayed before "[!] There was a problem processing campaign ID 129!"?

**Comment by turnerdb** [comment]
All taken care of.  Issue with the campaign.

Thanks.
