### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by Anjdroid** [chrismaddalena/GoReport#5]
Hi, 

my issue is that I keep getting the error: Details invalid API key when the GoReport tries to get the Data of the campaign. I have tried GoReport with two different GoPhish-es (both latest version), one was running directly on my computer and one was running on a server in the same domain and both times it cannot connect with the API key. I reset API key, reset the GoPhish server... not sure if im doing anything wrong or am I missing something?

**Comment by chrismaddalena** [comment]
Hey there,

That error is from the GoPhish server you are authenticating against. It means what it says, so my best guess is the config file might be pointing to a different server than the one that has that API key. You mentioned trying to different servers, so that could be the case.

Is the IP address in the gophish.config file the one tied to the API key also listed in there?

It really shouldn't matter, but I can't remember if I ever tested this to be sure, so make sure there are no extra characters at the beginning or end of the API key, too. Clear any whitespace and anything else you might find there.

Let me know if you have any luck.

**Comment by Anjdroid** [comment]
I always changed the gp_host to the admin server in question. I tested it again today and it still doesn't seem to be working.

This is my configuration..

gophish.config

**Comment by chrismaddalena** [comment]
Cool! No problem at all. I'm glad it was a simple fix. Tanks for letting me know!
